// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnoyrifntxvohgaptztp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxub3lyaWZudHh2b2hnYXB0enRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNTEwNzgsImV4cCI6MjA3OTcyNzA3OH0.y1FOe5FZAg-PExIlVMf7LLg0GWHIyTtzrnYd317WJlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});